DROP TABLE LIEFERDATUM;
DROP TABLE LIEFERT;
DROP TABLE VERPACKT;
DROP TABLE BÜROMITARBEITER;
DROP TABLE ABTEILUNGSPASS;
DROP TABLE ARTIKEL;
DROP TABLE BESTELLUNG;
DROP TABLE LAGERMITARBEITER;
DROP TABLE LIEFERANT;
DROP TABLE MITARBEITER;


COMMIT;

